from django.urls import path
from .views import (index, paper_reels, search_reels, update_reel, delete_reel,
                    add_purchase_order_detail, add_product, add_dispatch,
                    purchase_order, add_purchase_order_detailed,
                    delete_purchase_order, daily_program, production,
                    update_production_quantity, add_reel_to_production,
                    delete_production, products_detail, login_view, register_view,
                    logout_view, update_products, delete_products, delete_stock,
                    edit_program_view, delete_program_view, product_archive,
                    product_detail_archive, purchase_order_archive, purchase_order_detail_archive,
                    program_archive, production_archive, restore_reel, restore_products)

app_name = 'Corrugation'

urlpatterns = [
    path('', index, name='index'),
    path('delete-stock/<int:pk>/', delete_stock, name='delete_stock'),
    path('paper_reels/', paper_reels, name='paper_reels'),
    path('search_reels/', search_reels, name='search_reels'),
    path('update-reel/<int:pk>/', update_reel, name='update_reel'),
    path('delete-reel/<int:pk>/', delete_reel, name='delete_reel'),
    path('restore-reel/<int:pk>/', restore_reel, name='restore_reel'),
    path('purchase-order/', purchase_order, name='purchase_order'),
    path('purchase-order-archive/', purchase_order_archive, name='purchase_order_archive'),
    path('purchase-order-detail-archive/', purchase_order_detail_archive, name='purchase_order_detail_archive'),
    path('add-purchase-order-detail/', add_purchase_order_detail, name='add_purchase_order_detail'),
    path('add-purchase-order-detailed/', add_purchase_order_detailed, name='add_purchase_order_detailed'),
    path('add-product/', add_product, name='add_product'),
    path('product-archive/', product_archive, name='product_archive'),
    path('restore-product/<int:pk>/', restore_products, name='restore_products'),
    path('product-detail-archive/<int:pk>/', product_detail_archive, name='product_detail_archive'),
    path('update-products/<int:pk>/', update_products, name='update_products'),
    path('delete-products/<int:pk>/', delete_products, name='delete_products'),
    path('products-detail/<int:pk>/', products_detail, name='products_detail'),
    path('add-dispatch/', add_dispatch, name='add_dispatch'),
    path('delete-purchase-order/<int:pk>/', delete_purchase_order, name='delete_purchase_order'),
    path('daily-program/', daily_program, name='daily_program'),
    path('program-archive/', program_archive, name='program_archive'),
    path('edit-program-view/', edit_program_view, name='edit_program_view'),
    path('delete-program-view/', delete_program_view, name='delete_program_view'),
    path('production/', production, name='production'),
    path('production-archive/', production_archive, name='production_archive'),
    path('update-production-quantity/', update_production_quantity, name='update_production_quantity'),
    path('add-reel-to-production/', add_reel_to_production, name='add_reel_to_production'),
    path('delete-production/', delete_production, name='delete_production'),
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]
